config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :feedback

  resources :squad_dnas
  resources :squads do
    post 'import_squad_datum'
    post 'delete_squad_datum'
    post 'calculate_ratings'
    resources :squad_dnas
    resources :player
  end
  resources :squad_data
  get 'welcome/index'
  devise_for :users
  root 'welcome#index'

  post 'deletesquad' => 'player#deletesquad', as: :deletesquad

  post 'loadfiles' => 'player#loadfiles', as: :loadfiles
  post 'ratings' => 'player#ratings', as: :ratings
  post 'updatefiles' => 'player#updatefiles', as: :updatefiles

	post 'checkplayerratings' => 'player#checkplayerratings', as: :checkplayerratings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
	belongs_to :squad
end

app/controllers/player_controller.rb
require 'date'

class PlayerController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session
  
  def index
    @user = current_user

    @players = Player.where(user:current_user)
  end

  def indexsort
    @players = Player.all.sort_by {|p| -p.mtc_rat}
  end
  
  def indexdnasort
    @players = Player.all.sort_by {|p| -p.sqd_rat}
  end

  def show
    @player = Player.find(params[:id])
    @squad = Squad.find(params[:squad_id])
  end

  def deletesquad
    @players = Player.where(user:current_user)

    @players.delete_all

    redirect_to player_index_path
  end

  def updatefiles
    line_count = File.readlines("app/assets/csv/updatesquad.csv").size
    File.open("app/assets/csv/updatesquad.csv").each_line("\n").with_index(0) do |row, line_num|
      columns = row.split(";")

      unless (line_num == 0)
        # puts columns[0]
        player = Player.where(uid:columns[0]).first
        # puts player.name
        # player.condition = columns[2].to_i
        # player.mtc_shp = columns[3].to_i
        # player.overall_risk = columns[4]
        # player.injury = columns[5]
        # player.save
        puts columns
        player.update(
          condition: columns[2],
          mtc_shp: columns[3],
          overall_risk: columns[4],
          injury: columns[5],
          time_out: columns[6],
          squad_status: columns[7],
          g_mis: columns[8]
        )
      end
    end

    redirect_to player_index_path
  end

  def loadfiles
    line_count = File.readlines("app/assets/csv/SAP1.csv").size
    File.open("app/assets/csv/SAP1.csv").each_line("\n").with_index(0) do |row, line_num|

      columns = row.split(';')
      puts columns

      unless (line_num == 0)
        player = Player.new()
        player.uid = columns[0]
        player.name = columns[1]
        player.f_pt = columns[2]
        player.contract_type = columns[3]
        salary = 0
        salary = columns[4] if (columns[4] != "N/A")
        player.salary = salary
        player.appearance_fee = columns[5][1..-1].to_i
        player.unused_sub_fee = columns[6][1..-1].to_i
        expires = "1/1/1990".to_date
        player.expires = expires
        player.expires = Date.strptime(columns[7], '%m/%d/%Y') unless columns[7] == "-"
        player.offer_status = columns[8]
        player.new_wage = columns[9][1..-1].to_i
        new_date = "1/1/1990".to_date
        player.new_date = new_date
        player.new_date = Date.strptime(columns[10], '%m/%d/%Y') unless columns[10] == "-"
        player.waclg = columns[11][1..-1].to_i
        player.waclg_num = columns[12].to_i
        loan_expires = "1/1/1990".to_date
        player.loan_expires = loan_expires
        player.loan_expires = Date.strptime(columns[13], '%m/%d/%Y') unless columns[13] == "-"
        injured_on = "1/1/1990".to_date
        player.injured_on = injured_on
        player.injured_on = Date.strptime(columns[14], '%m/%d/%Y') unless columns[14] == "-"
        player.injury = columns[15]
        player.time_out = columns[16]
        player.condition = columns[17]
        player.mtc_shp = columns[18]
        player.sharpness = columns[19]
        player.player_status = columns[20]
        # dob = "1/1/1990".to_date
        # player.dob = dob
        puts columns[21]
        puts Date.strptime(columns[21][0..-16], '%m/%d/%Y')
        player.dob = Date.strptime(columns[21][0..-16], '%m/%d/%Y')
        # player.nat = columns[22].to_s
        # player.second_nat = columns[23].to_s
        # player.second_nat = "-" if columns[23] == nil
        # height = columns[24]
        # height = height[1..-3].split("'")
        # player.height = (height[0].to_i*12) + (height[1].to_i)
        puts columns[22]
        puts columns[22][0..-4].to_i
        player.height = columns[22][0..-4].to_i
        puts columns[23]
        puts columns[23][0..-5].to_i
        player.weight = columns[23][0..-5].to_i
        player.position = columns[24]
        player.second_position = columns[25]
        player.personality = columns[26]
        player.media_handling = columns[27]
        player.preferred_foot = columns[28]
        player.left_foot = columns[29]
        player.right_foot = columns[30]
        player.morale = columns[31]
        player.match_load = columns[32]
        player.training_load = columns[33]
        player.injury_susceptibility = columns[34]
        player.overall_risk = columns[35]
        player.workload = columns[36]
        player.training_happiness = columns[37]
        player.training_happiness_details = columns[38]
        player.position_role = columns[39]
        player.additional_focus = columns[40]
        player.loan_status = columns[41]
        player.on_loan_from = columns[42]
        player.squad_status = columns[43]
        player.transfer_status = columns[44]
        if columns[45][-1] == 'M'
          player.value = columns[45][1..-2].to_i*1000000
        elsif columns[45][-1] == 'K'
          player.value = columns[45][1..-2].to_i*1000
        else
          player.value = columns[45][1..-1].to_i
        end
        player.save
      end
    end
    File.open("app/assets/csv/SAP2.csv").each_line("\n").with_index(0) do |row, line_num|
      columns = row.split(";")

      unless (line_num == 0)
        player = Player.where(uid:columns[0]).first
        player.cor = columns[2].to_i
        player.cro = columns[3].to_i
        player.dri = columns[4].to_i
        player.fin = columns[5].to_i
        player.fir = columns[6].to_i
        player.fre = columns[7].to_i
        player.hea = columns[8].to_i
        player.lon = columns[9].to_i
        player.lth = columns[10].to_i
        player.mar = columns[11].to_i
        player.pas = columns[12].to_i
        player.pen = columns[13].to_i
        player.tck = columns[14].to_i
        player.tec = columns[15].to_i
        player.agg = columns[16].to_i
        player.ant = columns[17].to_i
        player.bra = columns[18].to_i
        player.cmp = columns[19].to_i
        player.cnt = columns[20].to_i
        player.dec = columns[21].to_i
        player.det = columns[22].to_i
        player.fla = columns[23].to_i
        player.ldr = columns[24].to_i
        player.otb = columns[25].to_i
        player.pos = columns[26].to_i
        player.tea = columns[27].to_i
        player.vis = columns[28].to_i
        player.wor = columns[29].to_i
        player.acc = columns[30].to_i
        player.agi = columns[31].to_i
        player.bal = columns[32].to_i
        player.jum = columns[33].to_i
        player.nat = columns[34].to_i
        player.pac = columns[35].to_i
        player.sta = columns[36].to_i
        player.str = columns[37].to_i
        player.aer = columns[38].to_i
        player.cmd = columns[39].to_i
        player.com = columns[40].to_i
        player.ecc = columns[41].to_i
        player.han = columns[42].to_i
        player.kic = columns[43].to_i
        player.onevone = columns[44].to_i
        player.ref = columns[45].to_i
        player.rus = columns[46].to_i
        player.pun = columns[47].to_i
        player.thr = columns[48].to_i
        player.save
      end
    end

    File.open("app/assets/csv/SAP3.csv").each_line("\n").with_index(0) do |row, line_num|
      columns = row.split(";")

      unless (line_num == 0)
        player = Player.where(uid:columns[0]).first
        player.ca = columns[2].to_i
        player.pa = columns[3].to_i
        player.yel = columns[4].to_i
        player.tgls_90 = columns[5].to_f
        player.tcon_90 = columns[6].to_f
        player.tck = columns[7].to_i
        player.tck_r = columns[8].to_f
        player.starts = columns[9].to_i
        player.shutouts = columns[10].to_i
        player.shot_90 = columns[11].to_f
        player.sht_90 = columns[12].to_f
        player.svt = columns[13].to_i
        player.svp = columns[14].to_i
        player.svh = columns[15].to_i
        player.red = columns[16].to_i
        player.pom = columns[17].to_i
        player.pts_gm = columns[18].to_f
        player.pen_r = columns[19].to_f
        player.pas_perc = columns[20].to_i
        player.ps_a_90 = columns[21].to_f
        player.off = columns[22].to_i
        player.mstks = columns[23].to_i
        player.gl_mst = columns[24].to_i
        player.last_gl = columns[25].to_i
        player.last_c = columns[26].to_i
        player.mins_gm = columns[27].to_i
        player.mins = columns[28].to_i
        player.last_5_games = columns[29].to_f
        player.k_tck = columns[30].to_i
        player.k_ps_90 = columns[31].to_f
        player.k_pas = columns[32].to_i
        player.k_hdrs = columns[33].to_i
        player.int_90 = columns[34].to_f
        player.hdr_perc = columns[35].to_i
        player.hdrs_w_90 = columns[36].to_f
        player.gls_90 = columns[37].to_f
        player.all_90 = columns[38].to_f
        player.conc = columns[39].to_i
        player.gls = columns[40].to_i
        player.g_mis = columns[41].to_i
        player.won = columns[42].to_i
        player.lost = columns[43].to_i
        player.d = columns[44].to_i
        player.gwin = columns[45].to_i
        player.fa = columns[46].to_i
        player.fls = columns[47].to_i
        player.drbpg = columns[48].to_i
        player.dist_90 = columns[49].to_f
        player.cr_c_a = columns[50].to_f
        player.ch_c_90 = columns[51].to_f
        player.av_rat = columns[52].to_f
        player.mins_gl = columns[53].to_i
        player.asts_90 = columns[54].to_f
        player.ast = columns[55].to_i
        player.apps = columns[56].to_i
        player.ps_c_90 = columns[57].to_f
        player.sqd_rat = 0
        player.mtc_rat = 0
        player.save
      end
    end

    redirect_to player_index_path
  end

  def ratings
    players = Player.all
    players.each do |player|
      cor = 0.5
      cro = 2.0
      dri = 1.5
      fin = 1.5
      fir = 1.5
      fre = 0.5
      hea = 1.0
      lon = 1.0
      lth = 0.5
      mar = 1.0
      pas = 2.0

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/player/index.html.erb
<h1>Player#index</h1>
<p>Find me in app/views/player/index.html.erb</p>

<%= button_to "Sort", player_indexsort_path %>

<%= button_to 'Delete Squad', deletesquad_path, :method=> "deletesquad" %>

<%= button_to 'Load Squad', loadfiles_path, :method=> "loadfiles" %>
<%= button_to 'Update Squad', updatefiles_path, :method=> "updatefiles" %>

<%= button_to 'Update Ratings', ratings_path, :method=> "ratings" %>

<%= button_to 'Load Shortlisted', checkplayerratings_path, :method=> "checkplayerratings" %>

<table class='table'>
  <thead class='thead-dark'>
    <tr>
      <th>UID</th>
      <th>Name</th>
      <th>Squad Rating</th>
      <th>Match Rating</th>
      <th>Full/Part Time</th>
      <th>Contract Type</th>
      <th>Wage (Salary)</th>
      <th>Appearance Fee</th>
      <th>Unused Sub Fee</th>
      <th>Contract Expiry Date</th>
      <th>New Contract Offer Status</th>
      <th>New Wage</th>
      <th>New Contract Date</th>
      <th>Wage after Club League Games</th>
      <th>Number of Club League Games Needed for New Wage</th>
      <th>Loan Expiry Date</th>
      <th>Injury Date</th>
      <th>Injury Desc.</th>
      <th>Injury Time Out</th>
      <th>Condition</th>
      <th>Match Shape</th>
      <th>Sharpness Desc.</th>
      <th>Player Status Desc.</th>
      <th>Date of Birth</th>
      <!-- <th>Nationality</th>
      <th>Second Nationality</th> -->
      <th>Height</th>
      <th>Weight</th>
      <th>Position</th>
      <th>Second Position</th>
      <th>Personality</th>
      <th>Media Handling</th>
      <th>Preferred Foot</th>
      <th>Left Foot</th>
      <th>Right Foot</th>
      <th>Morale</th>
      <th>Match Load</th>
      <th>Training Load</th>
      <th>Injury Susceptibility</th>
      <th>Overall Risk</th>
      <th>Workload</th>
      <th>Training Happiness</th>
      <th>Training Happiness Desc.</th>
      <th>Training Position/Role</th>
      <th>Training Addition Focus</th>
      <th>Loan Status</th>
      <th>On Loan From</th>
      <th>Squad Status</th>
      <th>Transfer Status</th>
      <th>Value</th>
      <th>Corners</th>
      <th>Crossing</th>
      <th>Dribbling</th>
      <th>Finishing</th>
      <th>First Touch</th>
      <th>Free Kicks</th>
      <th>Heading</th>
      <th>Long Shots</th>
      <th>Long Throws</th>
      <th>Marking</th>
      <th>Passing</th>
      <th>Penalty Taking</th>
      <th>Tackling</th>
      <th>Technical</th>
      <th>Aggression</th>
      <th>Anticipation</th>
      <th>Bravery</th>
      <th>Composure</th>
      <th>Concentration</th>
      <th>Decisions</th>
      <th>Determination</th>
      <th>Flair</th>
      <th>Leadership</th>
      <th>Off The Ball</th>
      <th>Positioning</th>
      <th>Teamwork</th>
      <th>Vision</th>
      <th>Workrate</th>
      <th>Acceleration</th>
      <th>Agility</th>
      <th>Balance</th>
      <th>Jumping</th>
      <th>Natural Fitness</th>
      <th>Pace</th>
      <th>Stamina</th>
      <th>Strength</th>
      <th>Aerial Reach</th>
      <th>Command of Area</th>
      <th>Communication</th>
      <th>Eccentricity</th>
      <th>Handling</th>
      <th>Kicking</th>
      <th>1V1</th>
      <th>Reflexes</th>
      <th>Rushing</th>
      <th>Punching</th>
      <th>Throwing</th>
      <th>Current Ability</th>
      <th>Potential Ability</th>
      <!-- <th>Current Reputation</th>
      <th>Home Reputation</th>
      <th>World Reputation</th> -->
      <th>Yellow Cards</th>
      <th>Team Goals /90</th>
      <th>Team Conceded /90</th>
      <th>Tackles /g</th>
      <th>Tackles Ratio</th>
      <th>Starts</th>
      <th>Shutouts</th>
      <th>Shots /90</th>
      <th>Shots On Target /90</th>
      <th>Saves Tipped</th>
      <th>Saves Parried</th>
      <th>Saves Held</th>
      <th>Red Cards</th>
      <th>Player of the Match</th>
      <th>Points Won /g</th>
      <th>Penalties Scored Ratio</th>
      <th>Pass Completion Ratio</th>
      <th>Pass Attempts /90</th>
      <th>Offsides</th>
      <th>Mistakes</th>
      <th>Mistakes Leading to Goal</th>
      <th>Minutes Since Last Goal</th>
      <th>Minutes Since Conceding</th>
      <th>Minutes /g</th>
      <th>Minutes</th>
      <th>Last 5 Games</th>
      <th>Key Tackles</th>
      <th>Key Passes /90</th>
      <th>Key Passes</th>
      <th>Key Headers</th>
      <th>Interceptions /90</th>
      <th>Header Ratio</th>
      <th>Header Won /90</th>
      <th>Goals /90</th>
      <th>Goals Allowed /90</th>
      <th>Goals Allowed</th>
      <th>Goals</th>
      <th>Games Missed in a Row</th>
      <th>Games Won</th>
      <th>Games Lost</th>
      <th>Games Drawn</th>
      <th>Game Win Ratio</th>
      <th>Fouls Against</th>
      <th>Fouls</th>
      <th>Dribbles /g</th>
      <th>Distance /90</th>
      <th>Cross Completed Ratio</th>
      <th>Chances Created /90</th>
      <th>Average Rating</th>
      <th>Average Minutes Per Goal</th>
      <th>Assists /90</th>
      <th>Assists</th>
      <th>Appearances</th>
      <th>Passes Completed /90</th>

    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.uid %></td>
        <td><%= player.name %></td>
        <td><%= player.sqd_rat %></td>
        <td><%= player.mtc_rat %></td>
        <td><%= player.f_pt %></td>
        <td><%= player.contract_type %></td>
        <td><%= player.salary %></td>
        <td><%= player.appearance_fee %></td>
        <td><%= player.unused_sub_fee %></td>
        <td><%= player.expires %></td>
        <td><%= player.offer_status %></td>
        <td><%= player.new_wage %></td>
        <td><%= player.new_date %></td>
        <td><%= player.waclg %></td>
        <td><%= player.waclg_num %></td>
        <td><%= player.loan_expires %></td>
        <td><%= player.injured_on %></td>
        <td><%= player.injury %></td>
        <td><%= player.time_out %></td>
        <td><%= player.condition %></td>
        <td><%= player.mtc_shp %></td>
        <td><%= player.sharpness %></td>
        <td><%= player.player_status %></td>
        <td><%= player.dob %></td>
        <!-- <td>< %= player.nat %></td>
        <td>< %= player.second_nat %></td> -->
        <td><%= player.height %></td>
        <td><%= player.weight %></td>
        <td><%= player.position %></td>
        <td><%= player.second_position %></td>
        <td><%= player.personality %></td>
        <td><%= player.media_handling %></td>
        <td><%= player.preferred_foot %></td>
        <td><%= player.left_foot %></td>
        <td><%= player.right_foot %></td>
        <td><%= player.morale %></td>
        <td><%= player.match_load %></td>
        <td><%= player.training_load %></td>
        <td><%= player.injury_susceptibility %></td>
        <td><%= player.overall_risk %></td>
        <td><%= player.workload %></td>
        <td><%= player.training_happiness %></td>
        <td><%= player.training_happiness_details %></td>
        <td><%= player.position_role %></td>
        <td><%= player.additional_focus %></td>
        <td><%= player.loan_status %></td>
        <td><%= player.on_loan_from %></td>
        <td><%= player.squad_status %></td>
        <td><%= player.transfer_status %></td>
        <td><%= player.value %></td>
        <td><%= player.cor %></td>
        <td><%= player.cro %></td>
        <td><%= player.dri %></td>
        <td><%= player.fin %></td>
        <td><%= player.fir %></td>
        <td><%= player.fre %></td>
        <td><%= player.hea %></td>
        <td><%= player.lon %></td>
        <td><%= player.lth %></td>
        <td><%= player.mar %></td>
        <td><%= player.pas %></td>
        <td><%= player.pen %></td>
        <td><%= player.tck %></td>
        <td><%= player.tec %></td>
        <td><%= player.agg %></td>
        <td><%= player.ant %></td>
        <td><%= player.bra %></td>
        <td><%= player.cmp %></td>
        <td><%= player.cnt %></td>
        <td><%= player.dec %></td>
        <td><%= player.det %></td>
        <td><%= player.fla %></td>
        <td><%= player.ldr %></td>
        <td><%= player.otb %></td>
        <td><%= player.pos %></td>
        <td><%= player.tea %></td>
        <td><%= player.vis %></td>
        <td><%= player.wor %></td>
        <td><%= player.acc %></td>
        <td><%= player.agi %></td>
        <td><%= player.bal %></td>
        <td><%= player.jum %></td>
        <td><%= player.nat %></td>
        <td><%= player.pac %></td>
        <td><%= player.sta %></td>
        <td><%= player.str %></td>
        <td><%= player.aer %></td>
        <td><%= player.cmd %></td>
        <td><%= player.com %></td>
        <td><%= player.ecc %></td>
        <td><%= player.han %></td>
        <td><%= player.kic %></td>
        <td><%= player.onevone %></td>
        <td><%= player.ref %></td>
        <td><%= player.rus %></td>
        <td><%= player.pun %></td>
        <td><%= player.thr %></td>
        <td><%= player.ca %></td>
        <td><%= player.pa %></td>
        <!-- <td>< %= player.cr %></td>
        <td>< %= player.hr %></td>
        <td>< %= player.wr %></td> -->
        <td><%= player.yel %></td>
        <td><%= player.tgls_90 %></td>
        <td><%= player.tcon_90 %></td>
        <td><%= player.tck %></td>
        <td><%= player.tck_r %></td>
        <td><%= player.starts %></td>
        <td><%= player.shutouts %></td>
        <td><%= player.shot_90 %></td>
        <td><%= player.sht_90 %></td>
        <td><%= player.svt %></td>
        <td><%= player.svp %></td>
        <td><%= player.svh %></td>
        <td><%= player.red %></td>
        <td><%= player.pom %></td>
        <td><%= player.pts_gm %></td>
        <td><%= player.pen_r %></td>
        <td><%= player.pas_perc %></td>
        <td><%= player.ps_a_90 %></td>
        <td><%= player.off %></td>
        <td><%= player.mstks %></td>
        <td><%= player.gl_mst %></td>
        <td><%= player.last_gl %></td>
        <td><%= player.last_c %></td>
        <td><%= player.mins_gm %></td>
        <td><%= player.mins %></td>
        <td><%= player.last_5_games %></td>
        <td><%= player.k_tck %></td>
        <td><%= player.k_ps_90 %></td>
        <td><%= player.k_pas %></td>
        <td><%= player.k_hdrs %></td>
        <td><%= player.int_90 %></td>
        <td><%= player.hdr_perc %></td>
        <td><%= player.hdrs_w_90 %></td>
        <td><%= player.gls_90 %></td>
        <td><%= player.all_90 %></td>
        <td><%= player.conc %></td>
        <td><%= player.gls %></td>
        <td><%= player.g_mis %></td>
        <td><%= player.won %></td>
        <td><%= player.lost %></td>
        <td><%= player.d %></td>
        <td><%= player.gwin %></td>
        <td><%= player.fa %></td>
        <td><%= player.fls %></td>
        <td><%= player.drbpg %></td>
        <td><%= player.dist_90 %></td>
        <td><%= player.cr_c_a %></td>
        <td><%= player.ch_c_90 %></td>
        <td><%= player.av_rat %></td>
        <td><%= player.mins_gl %></td>
        <td><%= player.asts_90 %></td>
        <td><%= player.ast %></td>
        <td><%= player.apps %></td>
        <td><%= player.ps_c_90 %></td>
      </tr>
    <% end %>
  </tbody>
</table>