config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :feedback

  resources :squad_dnas
  resources :squads do
    post 'import_squad_datum'
    post 'delete_squad_datum'
    post 'calculate_ratings'
    resources :squad_dnas
    resources :player
  end
  resources :squad_data
  get 'welcome/index'
  devise_for :users
  root 'welcome#index'

  post 'deletesquad' => 'player#deletesquad', as: :deletesquad

  post 'loadfiles' => 'player#loadfiles', as: :loadfiles
  post 'ratings' => 'player#ratings', as: :ratings
  post 'updatefiles' => 'player#updatefiles', as: :updatefiles

	post 'checkplayerratings' => 'player#checkplayerratings', as: :checkplayerratings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/squad_dna.rb
class SquadDna < ApplicationRecord
  belongs_to :squad
end

app/controllers/squad_dnas_controller.rb
class SquadDnasController < ApplicationController
  before_action :set_squad_dna, only: [:show, :edit, :update, :destroy]

  # GET /squad_dnas
  # GET /squad_dnas.json
  def index
    # @squad_dnas = SquadDna.all
    @squad = Squad.find(params[:squad_id])
    @squad_dnas = SquadDna.where(squad_id: @squad.id)
  end

  # GET /squad_dnas/1
  # GET /squad_dnas/1.json
  def show
    @squad = Squad.find(SquadDna.find(params[:id]).squad_id)
  end

  # GET /squad_dnas/new
  def new
    @squad_dna = SquadDna.new
    @squad = Squad.find(params[:squad_id])
  end

  # GET /squad_dnas/1/edit
  def edit
    @squad = Squad.find(params[:squad_id])
  end

  # POST /squad_dnas
  # POST /squad_dnas.json
  def create
    @squad_dna = SquadDna.new(squad_dna_params)

    respond_to do |format|
      if @squad_dna.save
        format.html { redirect_to @squad_dna, notice: 'Squad dna was successfully created.' }
        format.json { render :show, status: :created, location: @squad_dna }
      else
        format.html { render :new }
        format.json { render json: @squad_dna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squad_dnas/1
  # PATCH/PUT /squad_dnas/1.json
  def update
    respond_to do |format|
      if @squad_dna.update(squad_dna_params)
        format.html { redirect_to @squad_dna, notice: 'Squad dna was successfully updated.' }
        format.json { render :show, status: :ok, location: @squad_dna }
      else
        format.html { render :edit }
        format.json { render json: @squad_dna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squad_dnas/1
  # DELETE /squad_dnas/1.json
  def destroy
    @squad_dna.destroy
    respond_to do |format|
      format.html { redirect_to squad_squad_dnas_url(params[:squad_id]), notice: 'Squad dna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_squad_dna
      @squad_dna = SquadDna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def squad_dna_params
      params.require(:squad_dna).permit(:squad_id, :cor_m, :cro_m, :dri_m, :fin_m, :fir_m, :fre_m, :hea_m, :lon_m, :lth_m, :mar_m, :pas_m, :pen_m, :tck_m, :tec_m, :agg_m, :ant_m, :bra_m, :cmp_m, :cnt_m, :dec_m, :det_m, :fla_m, :ldr_m, :otb_m, :pos_m, :tea_m, :vis_m, :wor_m, :acc_m, :agi_m, :bal_m, :jum_m, :nat_m, :pac_m, :sta_m, :str_m, :aer_m, :cmd_m, :com_m, :ecc_m, :han_m, :kic_m, :onevone_m, :ref_m, :rus_m, :pun_m, :thr_m, :key_g_mis_h, :key_shp_h, :fir_g_mis_h, :fir_shp_h, :rot_g_mis_h, :rot_shp_h, :bac_g_mis_h, :bac_shp_h, :hot_g_mis_h, :hot_shp_h, :you_g_mis_h, :you_shp_h, :low_ris_h, :nor_ris_h, :inc_ris_h, :hig_ris_h, :ver_ris_h)
    end
end

app/helpers/squad_dnas_helper.rb
module SquadDnasHelper
end

app/views/squad_dnas/edit.html.erb
<h1>Editing Squad DNA</h1>

<%= render 'editform', squad_dna: @squad_dna %>

<%= link_to 'Show', @squad_dna %> |
<%= link_to 'Back', squad_squad_dnas_path(@squad) %>

app/views/squad_dnas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Squad DNA</h1>

<table class="table">
  <thead>
    <tr>
      <th>Squad</th>
      <th colspan="3"></th>
      <th>Cor m</th>
      <th>Cro m</th>
      <th>Dri m</th>
      <th>Fin m</th>
      <th>Fir m</th>
      <th>Fre m</th>
      <th>Hea m</th>
      <th>Lon m</th>
      <th>Lth m</th>
      <th>Mar m</th>
      <th>Pas m</th>
      <th>Pen m</th>
      <th>Tck m</th>
      <th>Tec m</th>
      <th>Agg m</th>
      <th>Ant m</th>
      <th>Bra m</th>
      <th>Cmp m</th>
      <th>Cnt m</th>
      <th>Dec m</th>
      <th>Det m</th>
      <th>Fla m</th>
      <th>Ldr m</th>
      <th>Otb m</th>
      <th>Pos m</th>
      <th>Tea m</th>
      <th>Vis m</th>
      <th>Wor m</th>
      <th>Acc m</th>
      <th>Agi m</th>
      <th>Bal m</th>
      <th>Jum m</th>
      <th>Nat m</th>
      <th>Pac m</th>
      <th>Sta m</th>
      <th>Str m</th>
      <th>Aer m</th>
      <th>Cmd m</th>
      <th>Com m</th>
      <th>Ecc m</th>
      <th>Han m</th>
      <th>Kic m</th>
      <th>Onevone m</th>
      <th>Ref m</th>
      <th>Rus m</th>
      <th>Pun m</th>
      <th>Thr m</th>
      <th>Key g mis h</th>
      <th>Key shp h</th>
      <th>Fir g mis h</th>
      <th>Fir shp h</th>
      <th>Rot g mis h</th>
      <th>Rot shp h</th>
      <th>Bac g mis h</th>
      <th>Bac shp h</th>
      <th>Hot g mis h</th>
      <th>Hot shp h</th>
      <th>You g mis h</th>
      <th>You shp h</th>
      <th>Low ris h</th>
      <th>Nor ris h</th>
      <th>Inc ris h</th>
      <th>Hig ris h</th>
      <th>Ver ris h</th>
      
    </tr>
  </thead>

  <tbody>
    <% @squad_dnas.each do |squad_dna| %>
      <tr>
        <td><%= squad_dna.squad.team_name %></td>
        <td><%= link_to 'Show', squad_squad_dna_path(params[:squad_id],squad_dna) %></td>
        <td><%= link_to 'Edit', edit_squad_squad_dna_path(params[:squad_id],squad_dna) %></td>
        <td><%= link_to 'Destroy', squad_squad_dna_path(params[:squad_id],squad_dna), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= squad_dna.cor_m %></td>
        <td><%= squad_dna.cro_m %></td>
        <td><%= squad_dna.dri_m %></td>
        <td><%= squad_dna.fin_m %></td>
        <td><%= squad_dna.fir_m %></td>
        <td><%= squad_dna.fre_m %></td>
        <td><%= squad_dna.hea_m %></td>
        <td><%= squad_dna.lon_m %></td>
        <td><%= squad_dna.lth_m %></td>
        <td><%= squad_dna.mar_m %></td>
        <td><%= squad_dna.pas_m %></td>
        <td><%= squad_dna.pen_m %></td>
        <td><%= squad_dna.tck_m %></td>
        <td><%= squad_dna.tec_m %></td>
        <td><%= squad_dna.agg_m %></td>
        <td><%= squad_dna.ant_m %></td>
        <td><%= squad_dna.bra_m %></td>
        <td><%= squad_dna.cmp_m %></td>
        <td><%= squad_dna.cnt_m %></td>
        <td><%= squad_dna.dec_m %></td>
        <td><%= squad_dna.det_m %></td>
        <td><%= squad_dna.fla_m %></td>
        <td><%= squad_dna.ldr_m %></td>
        <td><%= squad_dna.otb_m %></td>
        <td><%= squad_dna.pos_m %></td>
        <td><%= squad_dna.tea_m %></td>
        <td><%= squad_dna.vis_m %></td>
        <td><%= squad_dna.wor_m %></td>
        <td><%= squad_dna.acc_m %></td>
        <td><%= squad_dna.agi_m %></td>
        <td><%= squad_dna.bal_m %></td>
        <td><%= squad_dna.jum_m %></td>
        <td><%= squad_dna.nat_m %></td>
        <td><%= squad_dna.pac_m %></td>
        <td><%= squad_dna.sta_m %></td>
        <td><%= squad_dna.str_m %></td>
        <td><%= squad_dna.aer_m %></td>
        <td><%= squad_dna.cmd_m %></td>
        <td><%= squad_dna.com_m %></td>
        <td><%= squad_dna.ecc_m %></td>
        <td><%= squad_dna.han_m %></td>
        <td><%= squad_dna.kic_m %></td>
        <td><%= squad_dna.onevone_m %></td>
        <td><%= squad_dna.ref_m %></td>
        <td><%= squad_dna.rus_m %></td>
        <td><%= squad_dna.pun_m %></td>
        <td><%= squad_dna.thr_m %></td>
        <td><%= squad_dna.key_g_mis_h %></td>
        <td><%= squad_dna.key_shp_h %></td>
        <td><%= squad_dna.fir_g_mis_h %></td>
        <td><%= squad_dna.fir_shp_h %></td>
        <td><%= squad_dna.rot_g_mis_h %></td>
        <td><%= squad_dna.rot_shp_h %></td>
        <td><%= squad_dna.bac_g_mis_h %></td>
        <td><%= squad_dna.bac_shp_h %></td>
        <td><%= squad_dna.hot_g_mis_h %></td>
        <td><%= squad_dna.hot_shp_h %></td>
        <td><%= squad_dna.you_g_mis_h %></td>
        <td><%= squad_dna.you_shp_h %></td>
        <td><%= squad_dna.low_ris_h %></td>
        <td><%= squad_dna.nor_ris_h %></td>
        <td><%= squad_dna.inc_ris_h %></td>
        <td><%= squad_dna.hig_ris_h %></td>
        <td><%= squad_dna.ver_ris_h %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<% if @squad_dnas.length == 1 %>
  
<% else %>
  <%= link_to 'New Squad Dna', new_squad_squad_dna_path(@squad) %>
<% end %>

<%= link_to 'Back to Squad', squad_path(@squad) %>

app/views/squad_dnas/new.html.erb
<h1>New Squad DNA</h1>

<%= render 'newform', squad_dna: @squad_dna %>

<%= link_to 'Back', squad_squad_dnas_path(@squad.id) %>

app/views/squad_dnas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Squad:</strong>
  <%= @squad_dna.squad.team_name %>
</p>

<p>
  <strong>Cor m:</strong>
  <%= @squad_dna.cor_m %>
</p>

<p>
  <strong>Cro m:</strong>
  <%= @squad_dna.cro_m %>
</p>

<p>
  <strong>Dri m:</strong>
  <%= @squad_dna.dri_m %>
</p>

<p>
  <strong>Fin m:</strong>
  <%= @squad_dna.fin_m %>
</p>

<p>
  <strong>Fir m:</strong>
  <%= @squad_dna.fir_m %>
</p>

<p>
  <strong>Fre m:</strong>
  <%= @squad_dna.fre_m %>
</p>

<p>
  <strong>Hea m:</strong>
  <%= @squad_dna.hea_m %>
</p>

<p>
  <strong>Lon m:</strong>
  <%= @squad_dna.lon_m %>
</p>

<p>
  <strong>Lth m:</strong>
  <%= @squad_dna.lth_m %>
</p>

<p>
  <strong>Mar m:</strong>
  <%= @squad_dna.mar_m %>
</p>

<p>
  <strong>Pas m:</strong>
  <%= @squad_dna.pas_m %>
</p>

<p>
  <strong>Pen m:</strong>
  <%= @squad_dna.pen_m %>
</p>

<p>
  <strong>Tck m:</strong>
  <%= @squad_dna.tck_m %>
</p>

<p>
  <strong>Tec m:</strong>
  <%= @squad_dna.tec_m %>
</p>

<p>
  <strong>Agg m:</strong>
  <%= @squad_dna.agg_m %>
</p>

<p>
  <strong>Ant m:</strong>
  <%= @squad_dna.ant_m %>
</p>

<p>
  <strong>Bra m:</strong>
  <%= @squad_dna.bra_m %>
</p>

<p>
  <strong>Cmp m:</strong>
  <%= @squad_dna.cmp_m %>
</p>

<p>
  <strong>Cnt m:</strong>
  <%= @squad_dna.cnt_m %>
</p>

<p>
  <strong>Dec m:</strong>
  <%= @squad_dna.dec_m %>
</p>

<p>
  <strong>Det m:</strong>
  <%= @squad_dna.det_m %>
</p>

<p>
  <strong>Fla m:</strong>
  <%= @squad_dna.fla_m %>
</p>

<p>
  <strong>Ldr m:</strong>
  <%= @squad_dna.ldr_m %>
</p>

<p>
  <strong>Otb m:</strong>
  <%= @squad_dna.otb_m %>
</p>

<p>
  <strong>Pos m:</strong>
  <%= @squad_dna.pos_m %>
</p>

<p>
  <strong>Tea m:</strong>
  <%= @squad_dna.tea_m %>
</p>

<p>
  <strong>Vis m:</strong>
  <%= @squad_dna.vis_m %>
</p>

<p>
  <strong>Wor m:</strong>
  <%= @squad_dna.wor_m %>
</p>

<p>
  <strong>Acc m:</strong>
  <%= @squad_dna.acc_m %>
</p>

<p>
  <strong>Agi m:</strong>
  <%= @squad_dna.agi_m %>
</p>

<p>
  <strong>Bal m:</strong>
  <%= @squad_dna.bal_m %>
</p>

<p>
  <strong>Jum m:</strong>
  <%= @squad_dna.jum_m %>
</p>

<p>
  <strong>Nat m:</strong>
  <%= @squad_dna.nat_m %>
</p>

<p>
  <strong>Pac m:</strong>
  <%= @squad_dna.pac_m %>
</p>

<p>
  <strong>Sta m:</strong>
  <%= @squad_dna.sta_m %>
</p>

<p>
  <strong>Str m:</strong>
  <%= @squad_dna.str_m %>
</p>

<p>
  <strong>Aer m:</strong>
  <%= @squad_dna.aer_m %>
</p>

<p>
  <strong>Cmd m:</strong>
  <%= @squad_dna.cmd_m %>
</p>

<p>
  <strong>Com m:</strong>
  <%= @squad_dna.com_m %>
</p>

<p>
  <strong>Ecc m:</strong>
  <%= @squad_dna.ecc_m %>
</p>

<p>
  <strong>Han m:</strong>
  <%= @squad_dna.han_m %>
</p>

<p>
  <strong>Kic m:</strong>
  <%= @squad_dna.kic_m %>
</p>

<p>
  <strong>Onevone m:</strong>
  <%= @squad_dna.onevone_m %>
</p>

<p>
  <strong>Ref m:</strong>
  <%= @squad_dna.ref_m %>
</p>

<p>
  <strong>Rus m:</strong>
  <%= @squad_dna.rus_m %>
</p>

<p>
  <strong>Pun m:</strong>
  <%= @squad_dna.pun_m %>
</p>

<p>
  <strong>Thr m:</strong>
  <%= @squad_dna.thr_m %>
</p>

<p>
  <strong>Key g mis h:</strong>
  <%= @squad_dna.key_g_mis_h %>
</p>

<p>
  <strong>Key shp h:</strong>
  <%= @squad_dna.key_shp_h %>
</p>

<p>
  <strong>Fir g mis h:</strong>
  <%= @squad_dna.fir_g_mis_h %>
</p>

<p>
  <strong>Fir shp h:</strong>
  <%= @squad_dna.fir_shp_h %>
</p>

<p>
  <strong>Rot g mis h:</strong>
  <%= @squad_dna.rot_g_mis_h %>
</p>

<p>
  <strong>Rot shp h:</strong>
  <%= @squad_dna.rot_shp_h %>
</p>

<p>
  <strong>Bac g mis h:</strong>
  <%= @squad_dna.bac_g_mis_h %>
</p>

<p>
  <strong>Bac shp h:</strong>
  <%= @squad_dna.bac_shp_h %>
</p>

<p>
  <strong>Hot g mis h:</strong>
  <%= @squad_dna.hot_g_mis_h %>
</p>

<p>
  <strong>Hot shp h:</strong>
  <%= @squad_dna.hot_shp_h %>
</p>

<p>
  <strong>You g mis h:</strong>
  <%= @squad_dna.you_g_mis_h %>
</p>

<p>
  <strong>You shp h:</strong>
  <%= @squad_dna.you_shp_h %>
</p>

<p>
  <strong>Low ris h:</strong>
  <%= @squad_dna.low_ris_h %>
</p>

<p>
  <strong>Nor ris h:</strong>
  <%= @squad_dna.nor_ris_h %>
</p>

<p>
  <strong>Inc ris h:</strong>
  <%= @squad_dna.inc_ris_h %>
</p>

<p>
  <strong>Hig ris h:</strong>
  <%= @squad_dna.hig_ris_h %>
</p>

<p>
  <strong>Ver ris h:</strong>
  <%= @squad_dna.ver_ris_h %>
</p>

<%= link_to 'Edit', edit_squad_squad_dna_path(@squad, @squad_dna) %> |
<%= link_to 'Back', squad_squad_dnas_path(@squad) %>