config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :feedback

  resources :squad_dnas
  resources :squads do
    post 'import_squad_datum'
    post 'delete_squad_datum'
    post 'calculate_ratings'
    resources :squad_dnas
    resources :player
  end
  resources :squad_data
  get 'welcome/index'
  devise_for :users
  root 'welcome#index'

  post 'deletesquad' => 'player#deletesquad', as: :deletesquad

  post 'loadfiles' => 'player#loadfiles', as: :loadfiles
  post 'ratings' => 'player#ratings', as: :ratings
  post 'updatefiles' => 'player#updatefiles', as: :updatefiles

	post 'checkplayerratings' => 'player#checkplayerratings', as: :checkplayerratings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/squad.rb
class Squad < ApplicationRecord
  belongs_to :user
	has_many :players, dependent: :destroy
	has_many :squad_dnas, dependent: :destroy
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  before_action :set_squad, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction  

  # GET /squads
  # GET /squads.json
  def index
    @squads = Squad.all.where(user_id: current_user.id)
  end

  # GET /squads/1
  # GET /squads/1.json
  def show
    @squad_datum = @user.squad_datum
    @players = @squad.players.order("#{sort_column} #{sort_direction}")

    @squad_dna = SquadDna.where(squad_id: @squad.id)
  end

  # GET /squads/new
  def new
    @squad = Squad.new
    @user = current_user
  end

  # GET /squads/1/edit
  def edit
  end

  # POST /squads
  # POST /squads.json
  def create
    @squad = Squad.new(squad_params)

    respond_to do |format|
      if @squad.save
        format.html { redirect_to @squad, notice: 'Squad was successfully created.' }
        format.json { render :show, status: :created, location: @squad }
      else
        format.html { render :new }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squads/1
  # PATCH/PUT /squads/1.json
  def update
    respond_to do |format|
      if @squad.update(squad_params)
        format.html { redirect_to @squad, notice: 'Squad was successfully updated.' }
        format.json { render :show, status: :ok, location: @squad }
      else
        format.html { render :edit }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squads/1
  # DELETE /squads/1.json
  def destroy
    @squad.destroy
    respond_to do |format|
      format.html { redirect_to squads_url, notice: 'Squad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_squad_datum
    squad = Squad.find(params[:squad_id])
    players = Player.where(squad_id: squad.id)

    players.delete_all

    redirect_to squad_path(squad)
  end

  def import_squad_datum
    logger.debug(params[:squad_id])
    logger.debug(params[:id])

    squad = Squad.find(params[:squad_id])
    puts "[ ~~~ -- . SQUAD . -- ~~~ ]"
    puts squad
    puts squad.team_name
    user = User.find(squad.user_id)
    puts "[ ~~~ -- . USER . -- ~~~ ]"
    puts user
    puts user.email
    squad_datum = SquadDatum.where(user_id: user.id).first

    squad_datum.load_squad_data.each_line("\n").with_index(0) do |row, line_num|
      columns = row.split(';')

      unless (line_num == 0)
        player = Player.new()
        player.squad = squad
        player.uid = columns[0]
        player.name = columns[1]
        player.squad_status = columns[2]
        player.age = columns[3]
        player.height = columns[4]
        player.weight = columns[5]
        player.position = columns[6]
        player.second_position = columns[7]
        player.strength = columns[8]
        player.weakness = columns[9]
        player.condition = columns[10]
        player.mtc_shp = columns[11]
        player.g_mis = columns[12]
        player.overall_risk = columns[13]
        player.injury = columns[14]
        player.time_out = columns[15]
        player.cor = columns[16].to_i
        player.cro = columns[17].to_i
        player.dri = columns[18].to_i
        player.fin = columns[19].to_i
        player.fir = columns[20].to_i
        player.fre = columns[21].to_i
        player.hea = columns[22].to_i
        player.lon = columns[23].to_i
        player.lth = columns[24].to_i
        player.mar = columns[25].to_i
        player.pas = columns[26].to_i
        player.pen = columns[27].to_i
        player.tck = columns[28].to_i
        player.tec = columns[29].to_i
        player.agg = columns[30].to_i
        player.ant = columns[31].to_i
        player.bra = columns[32].to_i
        player.cmp = columns[33].to_i
        player.cnt = columns[34].to_i
        player.dec = columns[35].to_i
        player.det = columns[36].to_i
        player.fla = columns[37].to_i
        player.ldr = columns[38].to_i
        player.otb = columns[39].to_i
        player.pos = columns[40].to_i
        player.tea = columns[41].to_i
        player.vis = columns[42].to_i
        player.wor = columns[43].to_i
        player.acc = columns[44].to_i
        player.agi = columns[45].to_i
        player.bal = columns[46].to_i
        player.jum = columns[47].to_i
        player.nat = columns[48].to_i
        player.pac = columns[49].to_i
        player.sta = columns[50].to_i
        player.str = columns[51].to_i
        player.aer = columns[52].to_i
        player.cmd = columns[53].to_i
        player.com = columns[54].to_i
        player.ecc = columns[55].to_i
        player.han = columns[56].to_i
        player.kic = columns[57].to_i
        player.onevone = columns[58].to_i
        player.ref = columns[59].to_i
        player.rus = columns[60].to_i
        player.pun = columns[61].to_i
        player.thr = columns[62].to_i

        player.sqd_rat = 0
        player.mtc_rat = 0
        
        player.pos_st = 0
        player.pos_aml = 0
        player.pos_amc = 0
        player.pos_amr = 0
        player.pos_ml = 0
        player.pos_mc = 0
        player.pos_mr = 0
        player.pos_dm = 0
        player.pos_wbl = 0
        player.pos_wbr = 0
        player.pos_dl = 0
        player.pos_dc = 0
        player.pos_dr = 0
        player.pos_sw = 0
        player.pos_gk = 0

        pos0 = player.position.split(', ')
        sec_pos0 = player.second_position.split(', ')
        pos0.each do |t|
          temp = t.split(' (')
          positions = temp[0].split('/')
          sides = temp[1][0..-2] if temp[1] != nil

          positions.each do |pos|
            case pos
            when "ST"
              player.pos_st = 1
            when "AM"
              player.pos_amr = 1 if sides.include? "R"
              player.pos_amc = 1 if sides.include? "C"
              player.pos_aml = 1 if sides.include? "L"
            when "M"
              player.pos_mr = 1 if sides.include? "R"
              player.pos_mc = 1 if sides.include? "C"
              player.pos_ml = 1 if sides.include? "L"
            when "DM"
              player.pos_dm = 1
            when "WB"
              player.pos_wbr = 1 if sides.include? "R"
              player.pos_wbl = 1 if sides.include? "L"
            when "D"
              player.pos_dr = 1 if sides.include? "R"
              player.pos_dc = 1 if sides.include? "C"
              player.pos_dl = 1 if sides.include? "L"
            when "SW"
              player.pos_dm = 1
            when "GK"
              player.pos_gk = 1
            end
          end
        end

        sec_pos0.each do |t|
          temp = t.split(' (')
          positions = temp[0].split('/')
          sides = temp[1][0..-2] if temp[1] != nil

          positions.each do |pos|
            case pos
            when "ST"
              player.pos_st = 2
            when "AM"
              player.pos_amr = 2 if sides.include? "R"
              player.pos_amc = 2 if sides.include? "C"
              player.pos_aml = 2 if sides.include? "L"
            when "M"
              player.pos_mr = 2 if sides.include? "R"
              player.pos_mc = 2 if sides.include? "C"
              player.pos_ml = 2 if sides.include? "L"
            when "DM"
              player.pos_dm = 2
            when "WB"
              player.pos_wbr = 2 if sides.include? "R"
              player.pos_wbl = 2 if sides.include? "L"
            when "D"
              player.pos_dr = 2 if sides.include? "R"
              player.pos_dc = 2 if sides.include? "C"
              player.pos_dl = 2 if sides.include? "L"
            when "SW"
              player.pos_dm = 2
            when "GK"
              player.pos_gk = 2
            end
          end
        end

        player.save
      end

    end

    redirect_to squad_path(squad)
  end

  def calculate_ratings
    squad = Squad.find(params[:squad_id])
    players = Player.where(squad_id: squad.id)
    squad_dna = SquadDna.where(squad_id: squad.id).first


    players.each do |player|
      if player.position == "GK"
        dna_rating = (player.fre * squad_dna.fre_m)+(player.pen * squad_dna.pen_m)+(player.tec * squad_dna.tec_m)+(player.agg * squad_dna.agg_m)+(player.ant * squad_dna.ant_m)+(player.bra * squad_dna.bra_m)+(player.cmp * squad_dna.cmp_m)+(player.cnt * squad_dna.cnt_m)+(player.dec * squad_dna.dec_m)+(player.det * squad_dna.det_m)+(player.fla * squad_dna.fla_m)+(player.ldr * squad_dna.ldr_m)+(player.otb * squad_dna.otb_m)+(player.pos * squad_dna.pos_m)+(player.tea * squad_dna.tea_m)+(player.vis * squad_dna.vis_m)+(player.wor * squad_dna.wor_m)+(player.acc * squad_dna.acc_m)+(player.agi * squad_dna.agi_m)+(player.bal * squad_dna.bal_m)+(player.jum * squad_dna.jum_m)+(player.nat * squad_dna.nat_m)+(player.pac * squad_dna.pac_m)+(player.sta * squad_dna.sta_m)+(player.str * squad_dna.str_m)+(player.aer * squad_dna.aer_m)+(player.cmd * squad_dna.cmd_m)+(player.com * squad_dna.com_m)+(player.ecc * squad_dna.ecc_m)+(player.han * squad_dna.han_m)+(player.kic * squad_dna.kic_m)+(player.onevone * squad_dna.onevone_m)+(player.ref * squad_dna.ref_m)+(player.rus * squad_dna.rus_m)+(player.pun * squad_dna.pun_m)+(player.thr * squad_dna.thr_m)
      else

app/helpers/squads_helper.rb
module SquadsHelper

	def sort_link(column, title = nil)
    title ||= column.titleize
		# title = "UID" if title == "Uid"
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fas fa-sort-up" : "fas fa-sort-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <i class='#{icon}'></i>".html_safe, {column: column, direction: direction}
  end
end

app/views/squads/_form.html.erb
<%= form_with(model: squad, local: true) do |form| %>
  <% if squad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(squad.errors.count, "error") %> prohibited this squad from being saved:</h2>

      <ul>
      <% squad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_name %>
    <%= form.text_field :team_name, id: :squad_datum_team_name %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :squad_datum_user_id, value: @user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/squads/_table.html.erb
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th class="center"><%= sort_link "uid", "UID" %></th>
      <th class="center"><%= sort_link "name", "Name" %></th>
      <th class="center"><%= sort_link "sqd_rat", "Squad Rating" %></th>
      <th class="center"><%= sort_link "mtc_rat", "Match Rating" %></th>
      <!-- <th>< %= sort_link "height", "Height" %></th>
      <th>< %= sort_link "weight", "Weight" %></th> -->
      <th class="center"><%= sort_link "position", "Position" %></th>
      <!-- <th>< %= sort_link "second_position", "Secondary Position" %></th>
      <th>< %= sort_link "strength", "Pro" %></th>
      <th>< %= sort_link "weakness", "Con" %></th> -->
      <th class="center"><%= sort_link "squad_status", "Squad Status" %></th>
      <th class="center"><%= sort_link "age", "Age" %></th>
      <th class="center"><%= sort_link "condition", "Condition" %></th>
      <th class="center"><%= sort_link "mtc_shp", "Match Sharpness" %></th>
      <th class="center"><%= sort_link "g_mis", "Games Missed in a Row" %></th>
      <th class="center"><%= sort_link "overall_risk", "Overall Risk" %></th>
      <th class="center"><%= sort_link "injury", "Injury" %></th>
      <th class="center"><%= sort_link "time_out", "Time Out" %></th>
      <!-- <th>< %= sort_link "cor", "Corners" %></th>
      <th>< %= sort_link "cro", "Crossing" %></th>
      <th>< %= sort_link "dri", "Dribbling" %></th>
      <th>< %= sort_link "fin", "Finishing" %></th>
      <th>< %= sort_link "fir", "First Touch" %></th>
      <th>< %= sort_link "fre", "Free Kicks" %></th>
      <th>< %= sort_link "hea", "Heading" %></th>
      <th>< %= sort_link "lon", "Long Shots" %></th>
      <th>< %= sort_link "lth", "Long Throws" %></th>
      <th>< %= sort_link "mar", "Marking" %></th>
      <th>< %= sort_link "pas", "Passing" %></th>
      <th>< %= sort_link "pen", "Penalty Taking" %></th>
      <th>< %= sort_link "tck", "Tackling" %></th>
      <th>< %= sort_link "tec", "Technical" %></th>
      <th>< %= sort_link "agg", "Aggression" %></th>
      <th>< %= sort_link "ant", "Anticipation" %></th>
      <th>< %= sort_link "bra", "Bravery" %></th>
      <th>< %= sort_link "cmp", "Composure" %></th>
      <th>< %= sort_link "con", "Concentration" %></th>
      <th>< %= sort_link "dec", "Decisions" %></th>
      <th>< %= sort_link "det", "Determination" %></th>
      <th>< %= sort_link "fla", "Flair" %></th>
      <th>< %= sort_link "lea", "Leadership" %></th>
      <th>< %= sort_link "otb", "Off The Ball" %></th>
      <th>< %= sort_link "pos", "Positioning" %></th>
      <th>< %= sort_link "tea", "Teamwork" %></th>
      <th>< %= sort_link "vis", "Vision" %></th>
      <th>< %= sort_link "wor", "Workrate" %></th>
      <th>< %= sort_link "acc", "Acceleration" %></th>
      <th>< %= sort_link "agi", "Agility" %></th>
      <th>< %= sort_link "bal", "Balance" %></th>
      <th>< %= sort_link "jum", "Jumping" %></th>
      <th>< %= sort_link "nat", "Natural Fitness" %></th>
      <th>< %= sort_link "pac", "Pace" %></th>
      <th>< %= sort_link "sta", "Stamina" %></th>
      <th>< %= sort_link "str", "Strength" %></th>
      <th>< %= sort_link "aer", "Aerial Reach" %></th>
      <th>< %= sort_link "cmd", "Command of Area" %></th>
      <th>< %= sort_link "comm", "Communication" %></th>
      <th>< %= sort_link "ecc", "Eccentricity" %></th>
      <th>< %= sort_link "han", "Handling" %></th>
      <th>< %= sort_link "kic", "Kicking" %></th>
      <th>< %= sort_link "onevone", "1V1" %></th>
      <th>< %= sort_link "ref", "Reflexes" %></th>
      <th>< %= sort_link "rus", "Rushing" %></th>
      <th>< %= sort_link "pun", "Punching" %></th>
      <th>< %= sort_link "thr", "Throwing" %></th> -->
    </tr>
  </thead>

  <tbody>
    <% players.each do |player| %>
      <tr>
        <td class="center"><%= player.uid %></td>
        <td class="center"><%= link_to player.name, squad_player_path(@squad, player) %></td>
        <td class="center"><%= number_with_precision(player.sqd_rat, :precision => 1) %></td>
        <td class="center"><%= number_with_precision(player.mtc_rat, :precision => 1) %></td>
        
        <!-- <td>< %= player.height %></td>
        <td>< %= player.weight %></td> -->
        <td class="center">
          <table class='pos-table'>
            <tr class='pos-tr'>
              <td class='pos-td'></td>
              <td class='pos-td'>
                <% if player.pos_st == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_st == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'></td>
            </tr>
            <tr class='pos-tr'>
              <td class='pos-td'>
                <% if player.pos_aml == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_aml == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_amc == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_amc == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_amr == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_amr == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
            </tr>
            <tr class='pos-tr'>
              <td class='pos-td'>
                <% if player.pos_ml == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_ml == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_mc == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_mc == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_mr == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_mr == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
            </tr>
            <tr class='pos-tr'>
              <td class='pos-td'>
                <% if player.pos_wbl == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_wbl == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_dm == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_dm == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_wbr == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_wbr == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
            </tr>
            <tr class='pos-tr'>
              <td class='pos-td'>
                <% if player.pos_dl == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_dl == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_dc == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_dc == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'>
                <% if player.pos_dr == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_dr == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
            </tr>
            <tr class='pos-tr'>
              <td class='pos-td'></td>
              <td class='pos-td'>
                <% if player.pos_sw == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_sw == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'></td>
            </tr>
            <tr class='pos-tr'>
              <td class='pos-td'></td>
              <td class='pos-td'>
                <% if player.pos_gk == 1 %>
                <i class="fas fa-circle green"></i>
                <% elsif player.pos_gk == 2 %>
                <i class="far fa-dot-circle yellow"></i>
                <% else %>
                <i class="far fa-circle grey"></i>
                <% end %>
              </td>
              <td class='pos-td'></td>
            </tr>
          </table>
        </td>
        <!-- <td>< %= player.second_position %></td>
        <td>< %= player.strength %></td>
        <td>< %= player.weakness %></td> -->
        <td class="center"><%= player.squad_status %></td>
        <td class="center"><%= player.age %></td>
        <td class="center"><%= player.condition %></td>
        <td class="center"><%= player.mtc_shp %></td>
        <td class="center"><%= player.g_mis %></td>
        <td class="center"><%= player.overall_risk %></td>
        <td class="center"><%= player.injury %></td>
        <td class="center"><%= player.time_out %></td>
        <!-- <td>< %= player.cor %></td>
        <td>< %= player.cro %></td>
        <td>< %= player.dri %></td>
        <td>< %= player.fin %></td>
        <td>< %= player.fir %></td>
        <td>< %= player.fre %></td>
        <td>< %= player.hea %></td>
        <td>< %= player.lon %></td>
        <td>< %= player.lth %></td>
        <td>< %= player.mar %></td>
        <td>< %= player.pas %></td>
        <td>< %= player.pen %></td>
        <td>< %= player.tck %></td>
        <td>< %= player.tec %></td>
        <td>< %= player.agg %></td>
        <td>< %= player.ant %></td>
        <td>< %= player.bra %></td>
        <td>< %= player.cmp %></td>
        <td>< %= player.cnt %></td>
        <td>< %= player.dec %></td>
        <td>< %= player.det %></td>
        <td>< %= player.fla %></td>
        <td>< %= player.ldr %></td>
        <td>< %= player.otb %></td>
        <td>< %= player.pos %></td>
        <td>< %= player.tea %></td>
        <td>< %= player.vis %></td>
        <td>< %= player.wor %></td>
        <td>< %= player.acc %></td>
        <td>< %= player.agi %></td>
        <td>< %= player.bal %></td>
        <td>< %= player.jum %></td>
        <td>< %= player.nat %></td>
        <td>< %= player.pac %></td>
        <td>< %= player.sta %></td>
        <td>< %= player.str %></td>
        <td>< %= player.aer %></td>
        <td>< %= player.cmd %></td>
        <td>< %= player.com %></td>
        <td>< %= player.ecc %></td>
        <td>< %= player.han %></td>
        <td>< %= player.kic %></td>
        <td>< %= player.onevone %></td>
        <td>< %= player.ref %></td>
        <td>< %= player.rus %></td>
        <td>< %= player.pun %></td>
        <td>< %= player.thr %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/squads/edit.html.erb
<h1>Editing Squad</h1>

<%= render 'form', squad: @squad %>

<%= link_to 'Show', @squad %> |
<%= link_to 'Back', squads_path %>

app/views/squads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Squads</h1>

<table class="table">
  <thead>
    <tr>
      <th>Team Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @squads.each do |squad| %>
      <tr>
        <td><%= link_to squad.team_name, squad %></td>
        <td><%= link_to 'Show', squad %></td>
        <td><%= link_to 'Edit', edit_squad_path(squad) %></td>
        <td><%= link_to 'Destroy', squad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Squad', new_squad_path %>

app/views/squads/new.html.erb
<h1>New Squad</h1>

<%= render 'form', squad: @squad %>

<%= link_to 'Back', squads_path %>

app/views/squads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @squad.team_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @squad.user.email %>
</p>


<% if @squad.players.length >=1 %>
	<%= button_to 'Delete Squad Data', squad_delete_squad_datum_path(@squad), class:"button is-warning" %>
<% else %>
	<%= button_to 'Import Squad Data', squad_import_squad_datum_path(@squad), class:"button is-primary" %>
<% end %>


<% if @squad_dna.empty? %>
	<%= link_to 'Squad DNA', squad_squad_dnas_path(@squad), class:"button is-primary is-small" %>
<% else %>
	<%= link_to 'Squad DNA', squad_squad_dnas_path(@squad), class:"button is-primary is-small" %><%= button_to 'Calculate Ratings', squad_calculate_ratings_path(@squad), class:"button is-info" %>
<% end %>






<%= render 'table', players: @players %>

<%= link_to 'Edit', edit_squad_path(@squad) %> |
<%= link_to 'Back', squads_path %>