config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :feedback

  resources :squad_dnas
  resources :squads do
    post 'import_squad_datum'
    post 'delete_squad_datum'
    post 'calculate_ratings'
    resources :squad_dnas
    resources :player
  end
  resources :squad_data
  get 'welcome/index'
  devise_for :users
  root 'welcome#index'

  post 'deletesquad' => 'player#deletesquad', as: :deletesquad

  post 'loadfiles' => 'player#loadfiles', as: :loadfiles
  post 'ratings' => 'player#ratings', as: :ratings
  post 'updatefiles' => 'player#updatefiles', as: :updatefiles

	post 'checkplayerratings' => 'player#checkplayerratings', as: :checkplayerratings

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedback
  # GET /feedback.json
  def index
    @feedback = Feedback.all
  end

  # GET /feedback/1
  # GET /feedback/1.json
  def show
  end

  # GET /feedback/new
  def new
    @feedback = Feedback.new
    @user = current_user
  end

  # GET /feedback/1/edit
  def edit
  end

  # POST /feedback
  # POST /feedback.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedback/1
  # PATCH/PUT /feedback/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedback/1
  # DELETE /feedback/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedback_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:data)
    end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/_form.html.erb
<%= form_for feedback, url: feedback_index_path do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3>I want to hear your feedback</h3>
    <textarea class="textarea" placeholder="It would be super awesome if this project included..." rows="5"></textarea>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/feedback/edit.html.erb
<h1>Editing Feedback</h1>

 <!-- < %= render 'form', feedback: @feedback %>

 < %= link_to 'Show', @feedback %> |
 < %= link_to 'Back', feedback_index_path %> -->

app/views/feedback/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedback</h1>

<table class="table">
  <thead>
    <tr>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedback.each do |feedback| %>
      <tr>
        <td><!-- < %= feedback.data %> --></td>
        <td><!-- < %= link_to 'Show', feedback %> --></td>
        <td><!-- < %= link_to 'Edit', edit_feedback_path(feedback) %> --></td>
        <td><!-- < %= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %> --></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedback/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedback_index_path %>

app/views/feedback/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
<!--   < %= simple_format(@feedback.data) %>
 --></p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedback_index_path %>